### ISSUE TITLE
AsyncPF tests fail sometimes

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#117]
E.g. here: https://travis-ci.org/probmods/webppl/jobs/67389328

**Comment by null-a** [comment]
The failure Andreas linked to happens when checking the normalization constant. (You can't tell that from the error message because I made a mistake. I'll fix that.)

I also occasionally see `Positive weight!!` thrown in the same test. (About once every 25 runs perhaps.)

You can run the test in question with:

```
nodeunit tests/test-inference.js -f "AsyncPF - simple"
```

**Comment by iffsid** [comment]
Thanks!
Yeah; that check with `Positive weight!!` was put in because of the polarity of the weight that's used to compute the branching factor for a particle.
I'm looking into why the normalization constant errors occasionally.

**Comment by iffsid** [comment]
I'm keeping this open for a little while longer just to see if anyone reports errors in-the-wild.
I ran repeated tests, about 100 times in a row, and I didn't see anything wrong come up.

**Comment by iffsid** [comment]
Correction made in commit e817c5238bc6cb9c0e407843c09d0ce2aa080546.

The issue arose due to the use of _hard_ factors, which could lead to situations when the computation of `Rnk`, the ratio between the current weight and the running weight, would be `NaN` because both numerator and denominator could be `0` when, say, the first two particles at an observation both incurred a `factor(-Infinity)` in their traces.

This correction selects the right case in the formulation to compute the branching and weights, and accounts for the ratio being `NaN`.
