### ISSUE TITLE
Unify treatment of importance distributions and custom MH proposers

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#119]
Currently, importance distributions can be added to erps within webppl, e.g. like this:

    var coin = withImportanceDist(FairCoin, makeCoin(.2))

By contrast, ERPs with custom MH proposers can currently only be constructed outside of webppl, e.g. like this:

    var gaussianDriftERP = new erp.ERP(
        erp.gaussianERP.sample,
        erp.gaussianERP.score,
        {proposer: gaussianProposer});

In the end, both approaches result in an ERP with an extra field (`importanceERP` and `proposer`, respectively), each of which has another ERP as its value. For importance sampling, this ERP is currently unparameterized, whereas for proposers, it takes the previous ERP value and the base ERP params as arguments.

It could be good to make the specification of proposers and importance distributions more analogous, maybe allowing both to be specified from within webppl.

**Comment by null-a** [comment]
#494 switches importance distributions to use the guide program style, partly addressing this issue.

Does anyone have thoughts about how drift kernels should look using this style? The obvious thing seems to be to try something like:

```
sample(Gaussian(0,1), {
  guide: function(prev) { return Gaussian(prev, 0.1) };
})
// for which we can also provide a convenient wrapper:
gaussianDrift(0, 1, 0.1);
```

Calling this kernel function in cps from handwritten inference code will probably be a pain, but at first glance it seems like it would work.

If we *do* choose to go this way, it probably makes sense for me to skip #231 and #308 and jump straight to this?

**Comment by dritchie** [comment]
I'm not a huge fan of the keyword `guide` being overloaded to mean different things in different contexts (i.e. importance dist vs. proposal dist), but otherwise I'm onboard with this approach.

In support of another (probably more long term) goal, it would be worth thinking about how to make this interface support more arbitrary proposals (i.e. compound stochastic functions beyond just sampling from a single distribution), while computing the correct acceptance probabilities / importance weights.

(There's also the as-of-yet-untouched question of how to support custom proposals to multiple variables, but that's a whole other can of worms, I think)

**Comment by null-a** [comment]
> I'm not a huge fan of the keyword guide being overloaded to mean different things in different contexts 

Great, yes, using a different keyword seems like a sensible idea to me.

**Comment by ngoodman** [comment]
@null-a i like your suggestion, with `guide` changed to `driftKernel` (or something like that). and yes, might as well go straight to this (skipping #231 and #308).

> In support of another (probably more long term) goal, it would be worth thinking about how to make this interface support more arbitrary proposals (i.e. compound stochastic functions beyond just sampling from a single distribution), while computing the correct acceptance probabilities / importance weights.

this is actually pretty tricky, due to multiple paths... the best solution i can think of involves enumerating to build a distribution and then using the driftKernel style above.

**Comment by null-a** [comment]
I've made a start on this. As expected dealing with cps is a pain, but it looks like it will work out.

I hope to submit a PR that implements this (and includes #231 and #308) in the next day or two.

**Comment by null-a** [comment]
@dritchie: Please could you offer some feedback on a work-in-progress implementation of this in incremental MH?

If what follows doesn't make much sense, let me know and I'll try to explain things better:

I ran into trouble calling the drift kernel function from incremental MH's proposal code. Specifically, with something like this:

```js
sample(Dist({}), {driftKernel: function(val) { return Dist({mean: val}) }})
```

... the function call in the drift kernel function was triggering [this error](https://github.com/probmods/webppl/blob/7de83cfb05e480285cbede993af6b1fc9434c598/src/inference/incrementalmh.js#L986) in my initial implementation.

The way I got it working, was to install the default coroutine (in-place of IMH) as the current coroutine while evaluating the kernel function. This *appears* to work, but perhaps there a better way?

(The reason I even tried this, is that I'd already realized that calling `sample` or `factor` within the kernel function was likely produce odd results. So I'd already had the idea of evaluating the kernel function with a special coroutine installed as a way of catching such things at run time.)

Here's [the commit](https://github.com/null-a/webppl/commit/688547438d914451129260968a32a59298e3a6cb) that implements this. The change isn't as significant as it looks - it's mostly just a case of using the new (cps) function [`getProposalDist`](https://github.com/null-a/webppl/commit/688547438d914451129260968a32a59298e3a6cb#diff-15276e7e8ba6f713f51a9fa026a32050R155) to get hold of the proposal distributions rather than the old non-cps way, which was something like this:

```js
var fwdPropDist = this.dist.driftKernel ? this.dist.driftKernel(oldval) : this.dist;
```

Also, if you could comment on how to handle the `options` object when creating `DistNode`s ([as mentioned here](https://github.com/null-a/webppl/commit/688547438d914451129260968a32a59298e3a6cb#diff-15276e7e8ba6f713f51a9fa026a32050R877)) I'd very much appreciate it!

**Comment by dritchie** [comment]
This looks like the right idea to me. If the IncrementalMH coroutine is left in place, then it'll attempt a cache lookup when the drift kernel function is called (I think this is because the compiler wraps the drift kernel function in `incrementalize`, which calls `cachelookup`?)

A few suggestions:
* Instead of `defaultCoroutine`, maybe use a special coroutine that throws meaningful errors when `sample` or `factor` are called (e.g. "can't call sample from within a drift kernel").
* `DistNode.prototype.registerInputChanges` also needs to take `options` as an additional argument and do an `updateProperty(this, `options`, options)`.
* The `DistNode` constructor and `registerInputChanges` can take `options` either directly or in any array. Probably best to put it in an array, to be consistent with the way `FactorNode` and `FunctionNode` work?

**Comment by null-a** [comment]
@dritchie: Thanks again for those pointers. I've clean up [the code](https://github.com/null-a/webppl/commit/c9cb6e73badc0b3dd51405a0cebac182a7c61277) and it's just about ready to go, but I have a couple follow-up questions I hope you can help with...

> DistNode.prototype.registerInputChanges also needs to take options as an additional argument and do an updateProperty(this,options, options).

* Can you think of a simple test I can write that will fail if I don't do this?
* Does the `updateProperty` need to happen [conditionally](https://github.com/null-a/webppl/blob/c9cb6e73badc0b3dd51405a0cebac182a7c61277/src/inference/incrementalmh.js#L132)? If so, do we need to do a deep equality check? I'd guess so, since the only arg is the `options` object, but then again that's likely to only contain a function (for the drift kernel) that is recreated on each execution anyway. So maybe do it unconditionally? Not sure...

**Comment by dritchie** [comment]
Yeah, I think the unconditional update is fine--the only reason to make one of these updates conditional is if we think we can avoid re-execution if we detect no changes, but drift kernels offer no such opportunity.

I haven't been able to think of a test case for this, though. It's conceivable (but maybe unlikely) that a program could choose different drift kernels depending on upstream values, and that not updating the kernel (i.e. sticking with the one that was present on the initial run) could lead to less-efficient inference...but this is hard to check for in a clean way.
