### ISSUE TITLE
Default parameters for ERP?

### ISSUE THREAD

**Issue by null-a** [probmods/webppl#187]
I've been caught out a few times by the fact that `flip()` is equivalent to `flip(0)`rather than `flip(0.5)`.

Does it make sense to set default parameters for `bernoulliERP` and perhaps other ERP?

**Comment by stuhlmueller** [comment]
I agree that `flip()` should be equivalent to `flip(0.5)`. I'm not sure we need ERP default parameters for that, in particular since there aren't that many ERPs where we would want this behavior. Would it be enough to just make the wrapper functions (such as `flip` and `gaussian` in `header.wppl`) provide default arguments to the ERP if insufficiently many arguments are given?

**Comment by null-a** [comment]
Yes. I don't feel a strong expectation that `sample(bernoulliERP, [])` or perhaps `sample(bernoulliERP)` would be equivalent to `sample(bernoulliERP, [0.5])` so handling this in the wrappers seems reasonable to me.

**Comment by null-a** [comment]
Closed by #195.
