### ISSUE TITLE
IncrementalMH: variableSupport test sometimes fails

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#210]
https://travis-ci.org/probmods/webppl/jobs/81432310

**Comment by null-a** [comment]
The idea of the `variableSupport` [model](https://github.com/probmods/webppl/blob/25fb30554cfec4e2c34cc627a243e92506184123/tests/test-data/stochastic/models/variableSupport.wppl) is that `val` is expected to be `true` in all possible executions. This particular failure is caused by `val` taking on some other value, so this looks like a bug.

**Comment by stuhlmueller** [comment]
List of builds where this test has failed:
- https://travis-ci.org/probmods/webppl/builds/81432307
- https://travis-ci.org/probmods/webppl/builds/81609532

**Comment by null-a** [comment]
This can be reproduced with:

````bash
RANDOM_SEED=401427718 nodeunit tests/test-inference.js -f 'IncrementalMH - variableSupport'
````
