### ISSUE TITLE
Make binomial approximation consistent and explicit

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#219]
Currently, binomial sampling uses N=10 as threshold for approximation, whereas scoring uses N=20. These should be consistent, and maybe higher as well. The error resulting from approximation for small N is surprising:

    repeat(10, function(){return binomial(.5, 11)})

    [ 6, 7.5, 6, 6.5, 6.5, 6.5, 3, 5, 6.5, 7.5 ]

We could also give a parameter to the binomial ERP that controls whether to use the approximation at all.

**Comment by null-a** [comment]
Also:

```js
Binomial({n: 2, p: 1}).score(2) // => NaN
```

**Comment by hawkrobe** [comment]
Just to be clear, #455 scrapped approximation for scoring, but not sampling, right? So now the issue here  isn't a different threshold, it's just that that sampling from a binomial uses the approximation but scoring doesn't? 

And the other example shows that the support isn't correct for boundary values of `p`? Should that be considered a separate issue, since I can imagine removing approximation from the sampler but still not building the ERP with the correct support?

**Comment by longouyang** [comment]
You're right that scoring is still wrong when `p` is 0 or 1 -- I'll submit a quick PR to fix that.

Re the sampler, the Ahrens and Dieter paper says that it should be exact but I just spotted a bug in our implementation -- we should be sampling from `beta(a,b)` where `a` and `b` are integers, but our code fails to give integers for odd `n`. I'll comb through `binomialSample` some more and submit a PR for it.

**Comment by longouyang** [comment]
I think we should close this PR.

The issue was that we use different approximation thresholds for sampling versus scoring but this is now obsolete (and it's not clear that, as phrased, this was an accurate description -- the sampling method we use isn't an "approximation").

We now always do exact scoring (#455, #464) and bugs in the sampler should now fixed (#471).
