### ISSUE TITLE
Fix particle filter with rejuvenation

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#25]
I can't test this right now, but it's likely not working correctly, even if current tests pass, for reasons that may be related to my rewrite using `cpsForEach`. To get started on resolving this issue, add assertions that check that the acceptance probability is always a valid number, not `NaN`.

**Comment by stuhlmueller** [comment]
Also, need to check that we copy the store whenever necessary.

**Comment by ngoodman** [comment]
I made a number of fixes in 50c165b7402fff0731e61bf9a48d01764308ef18. Some more testing is needed to make sure i found all the bugs... (I think the pfrj tests are turned off in the test set, so a first step would be turning them on...)

**Comment by stuhlmueller** [comment]
Neat, thanks! I turned on the tests.

**Comment by iffsid** [comment]
It appears to still be broken in some cases.
Consider the simple example below. The model tries to infer a category/object such that the distance of an instance of a particular category/object, a value, to a given reference value, is minimized.

```js
var model = ParticleFilterRejuv(function() {
  var refVal = 4;
  var aList = [[1,2],
               [5,6,7]];
  var objI = randomInteger(aList.length); // draw object index
  var obj = aList[objI];
  var valI = randomInteger(obj.length);   // draw value index
  var val = obj[valI];
  var score = Math.log(1 - Math.abs(val - refVal) / 10);
  console.log('Selecting object ' +
              obj + ' (at ' + objI + ') and value ' +
              val + ' (at ' + valI + ')');
  factor(score);
  return objI;
}, 100, 100);

print(model);
```

If we make the elements of the category/object space all have same dimensionality, i.e, if aList has elements of equal length, then things work fine. However, if the lengths are different, things break.

**Comment by ngoodman** [comment]
This doesn't have to do with PFR per se, it would happen in normal MH (check). It is because the domain of the ERP at `randomInteger(obj.length)` is changing. We are probably not currently resampling on domain change -- this is fairly subtle to do right without reducing value reuse for changes to other parameters.

**Comment by iffsid** [comment]
Yes, this happens in MH as well.
I got around this (in the SMC branch) by checking if the parameters were changed, and modifying `reuse` in `MH.prototype.sample` appropriately, but as you point out, this likely reduces the reuse rate for the process.
Basically, we'd need way to tell if `prev.val` is, or can be, in the support of the `erp` with new `params`.
In our case, we might be able to improve the reuse rate by perhaps annotating ERPs with whether they have infinite (or even independent-of-params) support, because then, we could just leave the value as is and let `erp.score` take care of the scoring appropriately.

**Comment by stuhlmueller** [comment]
> Basically, we'd need way to tell if prev.val is, or can be, in the support of the erp with new params.

Can't we just compute that? If parameters changed, compute new support, check if prev.val is still in it, and reuse if yes, resample if no. If there is no support function, follow the current always-reuse policy. Is this going to mess up the MH probabilities?

**Comment by ngoodman** [comment]
You can't resample only if pre.val is not in the new support. (Because the reverse might not trigger resampling.) You could have a policy to not re-use any time the support changes.

Overall, we should make sure ERP scoring functions are checking the domain. If that is done correctly, then MH is correct, and will simply reject proposals where the support changes and the current value is no longer in the support. (And note it can then exit early since we know the proposal prob is zero.)

**Comment by stuhlmueller** [comment]
What if you resample restricted to the new portion of the support (if prev.val is not in the new support; otherwise, reuse)? Then the reverse should always trigger resampling.

**Comment by ngoodman** [comment]
How this would work if the new support is a subset of the old support? That is, how does the reverse trigger resampling there?

**Comment by stuhlmueller** [comment]
Hmm. The proposed strategy only makes sense when neither support is entirely contained within the other. Maybe that's too specific a case to be worth thinking about - the more common case seems to be something like `(sample-integer n)`, where `n` grows and shrinks, so we'd be in the situation where supports are subsets.
