### ISSUE TITLE
Get eval working

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl#34]

**Comment by stuhlmueller** [comment]
To do this, we need a header function that applies all transforms to the string of interest, uses Javascript eval to evaluate the transformed string, and then passes the returned object to the continuation.

**Comment by stuhlmueller** [comment]
In fact, there's already `webppl_eval` [here](/probmods/webppl/blob/dev/src/main.js#L99), but it's currently not quite appropriate for this purpose (e.g. doesn't take store).

**Comment by null-a** [comment]
Does #157 close this?

**Comment by feste** [comment]
Nope, it still doesn't take a store I think.

**Comment by stuhlmueller** [comment]
Hmm. My first thought was that this should be closed (since `webpplEval` now takes `s, k, a, code` as arguments, so the first argument is the store). However, `run` evaluates the code with an empty store:

    eval.call(global, compiledCode)({}, k, '');

So, `webpplEval` as it is will empty the store for all subsequent computation. Similarly, the address is reset. This is a bug. To fix this, `run` could take store and address as optional arguments and pass them on to the result of the eval call. However, it may be simpler to just call `compile` and `eval` directly in `webpplEval`, and pass on store, address, and continuation there.

**Comment by null-a** [comment]
Closed by #177.
