### ISSUE TITLE
sampleWithFactor not working

### ISSUE THREAD

**Issue by williamleif** [probmods/webppl#36]
The sampleWithFactor function is broken in both master and dev branches. This means the dippl.org examples using that function are currently broken as well.

**Comment by stuhlmueller** [comment]
The cause of this issue is that `Enumerate.prototype.sampleWithFactor` and `Enumerate.prototype.sample` use the score function by calling it in non-tail position. More precisely, `Enumerate.prototype.sampleWithFactor` constructs a helper function as follows:

    coroutine.sample(s,cc,a,dist,params,
                     function(v){
                       var ret;
                       scoreFn(s, function(s, x){ret = x;}, a+"swf", v);
                       return ret;});

`Enumerate.prototype.sample` calls this helper function in a `for` loop. This isn't supported in cps style and causes problems now that we are using trampolining. For example, a compiled `scoreFn` may look like this:

    function (globalStore, _k50, address, v) {
      var _return = _k50;
      var _k51 = _return;
      var _test52 = v;
      _test52 ? _trampoline = function () {
        _k51(globalStore, 0);
      } : _trampoline = function () {
        _k51(globalStore, -Infinity);
      };
    }

So, it never returns and assigns a function to the global `_trampoline` variable, which would return a value to the continuation (`function(s, x){ret = x;}` above) if called. Assigning a local continuation to the global `_trampoline` variable is problematic, because it may override the actual top-level continuation.

One way to fix this is to use `cpsForEach` in `Enumerate.prototype.sample`, but maybe there is a simpler solution?

For now, I have commented-out the broken `Enumerate.prototype.sampleWithFactor` implementation, which makes `sampleWithFactor` semantically correct again (but no different from using sample and factor individually).
