### ISSUE TITLE
opening and reading file

### ISSUE THREAD

**Issue by zaddan** [probmods/webppl#370]
how do I open and read a file?

**Comment by longouyang** [comment]
You need to use the node core library [fs](https://nodejs.org/api/fs.html)

The way to do this in webppl is:

```js
var fs = require.call(null, 'fs');
var fileContents = fs.readFileSync('input.txt','utf8');
```

`fileContents` is a string that you can then process.

Note that, in ordinary Javascript, we could just write the first line as `var fs = require('fs')`. But we can't do this in webppl because the compiler transforms function calls in a way that breaks `require`; we tell webppl to not transform using the `.call` syntax

**Comment by zaddan** [comment]
I get the following error:


undefined:9

 var fs = require.call(null, 'fs');

             ^

ReferenceError: require is not defined

**Comment by longouyang** [comment]
Ah, it looks like there's something wrong with the way we run code from the webppl binary.

It should work if you first compile to javascript and then run the javascript file:

```sh
webppl foo.wppl --compile --out foo.js
node foo.js
```

@stuhlmueller do you have any idea why using `require` stopped working when calling webppl directly on a wppl file?

**Comment by mhtess** [comment]
For what it's worth, I use the library fs in a .js file in a [webppl package](http://webppl.readthedocs.org/en/master/packages.html#javascript-functions-and-libraries) to read .csv files, with something like 

```
var fs = require('fs');
var babyparse = require('babyparse');

function readCSV(filename){
  return babyparse.parse(fs.readFileSync(filename, 'utf8'));
};

module.exports = {
  readCSV: readCSV
};
```

**Comment by null-a** [comment]
I suspect it stopped working after [this commit](https://github.com/probmods/webppl/commit/3744dc77015ad838af0ee1a656914f705ddced20). 

`eval(code) => eval.call(global, code)`

It's not obvious to me that this should be reverted, so I think a simple package is the way to go until we have a better approach to IO.

I've started [webppl-fs](https://github.com/null-a/webppl-fs) which wraps `fs.readFileSync` and `fs.writeFileSync`, see the readme for details.

**Comment by longouyang** [comment]
Can we just do `eval(code)` if we're not running in the browser?

**Comment by null-a** [comment]
I'm not sure what you have in mind/how it helps?

If we're still concerned with making IO work, it seems to me we should address this more directly rather than by making `require.call(null, 'fs')` work.

Maybe we should move this discussion to the general IO issue #336, or specific issues e.g. #278.

**Comment by longouyang** [comment]
Sorry, I should have explained -- `eval(code)` makes `require.call(null, 'foo')` work on the command line again.

The main issue here seems to be getting `require` calls in code working (more general than IO) -- I'll open a new issue for that.
