### ISSUE TITLE
Post-hoc enumerating an ERP doesn't give the same support

### ISSUE THREAD

**Issue by longouyang** [probmods/webppl#411]
I expected this model:

```js
var foo = Enumerate(function() { return uniformDraw(['a','b'] })
console.log(foo.support())

var bar = Enumerate(function() { return foo.sample() })
console.log(bar.support())
```

To print `['b','a']` twice but instead I get:

```js
[ 'b', 'a' ]
[ 'a' ]
```

This seems problematic, given that many recursive models are natural to express in this way.

**Comment by mhtess** [comment]
If you write 
```
var bar = Enumerate(function() { return sample(foo) })
```
then you do recover `['b','a']` ?

**Comment by stuhlmueller** [comment]
I wonder if we should make `dist.sample()` inaccessible to webppl code so that users can't mistakenly use it instead of `sample(dist)`. The former is never correct, since it doesn't call the `sample` function of the current inference coroutine and so randomness is not accounted for.

Alternatively, we could make `dist.sample()` the recommended syntax, perhaps when we deal with #358.
