### ISSUE TITLE
syntax errors are now inscrutable

### ISSUE THREAD

**Issue by ngoodman** [probmods/webppl#478]
Simple syntax errors tend to throw inscrutable errors that make debugging hard. Example below. (I'm not positive, but I think this got worse with the new error handling.) Is there any way to get more useful information?

~~~
Line 87: Unexpected end of input
[... ) ( )  ...]
    at /Users/ngoodman/webppl/node_modules/sweet.js/lib/parser.js:1942

1941|         } else {
1942|             error = new Error('Line ' + lineNumber + ': ' + msg + tailingMsg);
      --------------------^
1943|             error.index = index;

Stack trace:
    at throwError (/Users/ngoodman/webppl/node_modules/sweet.js/lib/parser.js:1942:21)
    at readDelim (/Users/ngoodman/webppl/node_modules/sweet.js/lib/parser.js:4713:17)
    at readToken (/Users/ngoodman/webppl/node_modules/sweet.js/lib/parser.js:4612:35)
    at Object.read (/Users/ngoodman/webppl/node_modules/sweet.js/lib/parser.js:4765:28)
    at expand$2 (/Users/ngoodman/webppl/node_modules/sweet.js/lib/sweet.js:86:35)
    at parse (/Users/ngoodman/webppl/node_modules/sweet.js/lib/sweet.js:124:29)
    at Object.compile (/Users/ngoodman/webppl/node_modules/sweet.js/lib/sweet.js:130:19)
    at parse (/Users/ngoodman/webppl/src/main.js:55:24)
    at _compile (/Users/ngoodman/webppl/src/main.js:178:22)
    at Object.timeif (/Users/ngoodman/webppl/src/util.js:257:37)
~~~

**Comment by null-a** [comment]
> I'm not positive, but I think this got worse with the new error handling.

I think the only difference the new error handling makes here is the insertion of this (admittedly not very useful) bit:

```
1941|         } else {
1942|             error = new Error('Line ' + lineNumber + ': ' + msg + tailingMsg);
      --------------------^
1943|             error.index = index;
```

This bit comes from `sweet.js`:

```
Error: Line 87: Unexpected end of input
[... ) ( )  ...]
```

... which in general [is probably](https://github.com/probmods/webppl/issues/124#issuecomment-169516213) an improvement over the syntax errors we had prior to adding macros.

For example this program:

```js
f(foo, );
````

Gives this:

```
Line 1: Unexpected token )
[... foo , ) ;  ...]

<snip>
```

Which at least includes the line number and a decent clue about what the problem is.

> Is there any way to get more useful information?

Nothing straight-foward comes to mind. At some point we'll have to switch to a newer version of sweet.js, and we can hope that things have improved upstream. If not, I guess we'll have to put our own thing in front of sweet.js if we want something different.

**Comment by ngoodman** [comment]
that makes sense. 

if the line number was correct this would be useful, but it seems not to be (within wppl programs). perhaps this is because it's the line number after sticking on the header? any easy way to get the actual source line?

**Comment by null-a** [comment]
> perhaps this is because it's the line number after sticking on the header?

Looks like the program is parsed separately, so that shouldn't be a problem.

If I do:

```js
flip();
f(foo, );
```

... i get:

```
Line 2: Unexpected token )
[... foo , ) ;  ...]
```

I also tried a longer example and that worked too. Not sure what's happening in your example. If you share the code I'll take a look.

**Comment by ngoodman** [comment]
yeah... i tested again, and line numbers seem to be useful. (except when there's a missing bracket, and it give the last line of the file. nothing to do about that, though.)
