### ISSUE TITLE
Continuous scorers for sampling-based marginals

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#509]
Suppose I am working with a sample-based inference result for a continuous distribution, e.g.:

```
var dist = Infer({method: 'SMC', particles: 10000}, function() {
  var x = poisson(.5);
  var y = gaussian(2, 1);
  return x * y;
});
```

I sometimes want to compute (estimate) scores under distributions like this, but all values that haven't been sampled are outside of the support and thus have probability 0:

```
dist.score(1)  // => -Infinity
```

I can currently approach this by manually constructing a kernel density scorer:

```
var kdeScore = function(dist, value, sigma) {  
  return Math.log(expectation(Infer({ method: 'enumerate' }, function() {
    var x = sample(dist);
    return Math.exp(Gaussian({ mu: x, sigma: sigma }).score(value));
  })));
};

kdeScore(dist, 1, .1);  // => ~ -2.5
```

However, (1) this is probably an inefficient way of doing this computation and (2) it would be nice to package up scorer and sampler in a distribution object.

This seems like a fairly common use case, so we might want to provide primitives.

**Comment by null-a** [comment]
Related: #369

**Comment by longouyang** [comment]
I've been looking into density estimation for viz stuff lately and found that the standard KDE with a Gaussian kernel can behave poorly near the bounds of your support (because this kernel doesn't *know* that there are bounds).

If your support is bounded on both ends then a [Beta kernel](www.sciencedirect.com/science/article/pii/S0167947399000109) seems suitable and if it's bounded at only one end, then maybe use [Gamma kernels](http://www.ism.ac.jp/editsec/aism/pdf/052_3_0471.pdf).

**Comment by stuhlmueller** [comment]
Good advice - thanks Long!

**Comment by longouyang** [comment]
Also, there's a lighter-weight approach where you [transform your variables](http://thirdorderscientist.org/homoclinic-orbit/2013/10/24/kernel-density-estimation-for-random-variables-with-bounded-support-mdash-the-transformation-trick). I suspect the Beta and Gamma methods are more accurate than this, but this would work if accuracy isn't super important.

**Comment by longouyang** [comment]
A final reference: [a complicated but robust-looking method based on linear diffusion.](https://arxiv.org/pdf/1011.2602.pdf)

**Comment by mcfrank** [comment]
+1 for this - @hrlarry and I have been working on reimplementing the super simple beta-binomial model in [this paper](http://langcog.stanford.edu/papers/F-cogsci2014.pdf) and run into this problem, since we have teachers doing inference about the binomial inferences.

Minimal-ish WE of where this causes problems:
https://github.com/mcfrank/teaching/blob/master/webppl/single_student_with_teacher.js

**Comment by longouyang** [comment]
For your particular problem, you can rewrite it to directly sample from the posterior over learner weights because Beta is a conjugate prior to Binomial.

**Comment by mcfrank** [comment]
thanks, Long. I'm aware that this is a conjugate model. :) How does one
exploit conjugacy in this case?

Reference:
http://docs.webppl.org/en/master/search.html?q=conjugate&check_keywords=yes&area=default#

Mike

**Comment by longouyang** [comment]
Ah -- my previous comment was inaccurate. The benefit of conjugacy here isn't that it lets you directly sample from the posterior -- the benefit is that you avoid constructing a sample-based approximation at all.

I believe that you can rewrite your learner function to return a `Beta` distribution with updated pseudocounts. That will let you score arbitrary weight values inside of the teacher.

**Comment by mcfrank** [comment]
Ah, thank you - so just to confirm, you're saying that we need to hard code
that we're updating the parameters on a beta distribution, e.g. make the
function a beta-distribution update (no `Infer`) at all?

**Comment by longouyang** [comment]
Yes, that's right. In addition to obviating the need for density estimation, I think this will also be faster.
