### ISSUE TITLE
PruneERP: remove states with 0 probability

### ISSUE THREAD

**Issue by mhtess** [probmods/webppl#59]
```
var model = function(){
	Enumerate(function(){
	var state = uniformDraw([0,1,2,3])
	factor(state>0? 0 : -Infinity)
	return state
	})}


var model2 = function(){
	Enumerate(function(){
	var state = sample(model())
	console.log(state)
	return state
	})
}

model2()
```
Calling `model2()` enumerates over all states, including the state previously set to have 0 probability (from `model1()`). 

Would be nice to 

+ throw a warning when this happens
+ have an option to automatically remove (i.e. Prune) this state out

This could have some efficiency gains, because you're not spending time on states with 0 probability.

**Comment by mhtess** [comment]
It seems I have my cake now but I want it too. I am using the following to write ERPs to CSVs...
```
var posterior = map(
  function(value){
    value.concat(Math.exp(results.score([], value)))
  },
  results.support([]))
```

With 0 probability states removed, it's no longer that simple. Can we either make pruneERP a selective thing, or make a writeERP function?

**Comment by stuhlmueller** [comment]
I'll look into it.

**Comment by mhtess** [comment]
I found a solution that works in my situation

```
var posterior = map(
  function(value){
    value.concat(Math.exp(results.score([], value)))
  },
  theOrderOfTheSupportThatIWant)
```

Of course, you may not know the order that you want in advance (though for small scale, categorical data, it's likely you will).

**Comment by stuhlmueller** [comment]
I thought about this a little more and changed the pruning from happening in `makeMarginalERP` to a check in `Enumerate.exit` so that we only add non-zero scores to marginal distribution. The contract for `makeMarginalERP` is more sensible this way. 

It is debatable whether zero-probability states should be pruned by default, but I think the answer is yes, because that will be consistent with bailing out of inference early, in which case we never learn which marginal value it is that has probability 0 (see issue #57).

If you need a fixed support including some zero-probability values, a solution similar to the one MH found is always possible.

**Comment by ngoodman** [comment]
i agree with this -- the support of an ERP really should be all and only the elements with non-zero probability.
