### ISSUE TITLE
Add helper to throw error and generate stack trace

### ISSUE THREAD

**Issue by tbenst** [probmods/webppl#616]
CPS spits out an error if "throw" is used in webppl code. It would be nice to be able to throw exceptions for debugging purposes

**Comment by null-a** [comment]
There are a couple of work-arounds: 1) Use `assert.ok` or 2) use [`util.fatal`](https://github.com/probmods/webppl/blob/1c3cd24147bbeede50d42f24ab666d64a9ac41f9/src/util.js#L283).

If this is a thing we need, perhaps we make `util.fatal` easier to access (as `fatal` or `fail` perhaps) and document it. We might also switch it to throwing an error rather than a string now that we have something like stack traces.
