### ISSUE TITLE
cannot combine tensors created in JavaScript and webppl

### ISSUE THREAD

**Issue by tbenst** [probmods/webppl#617]
If `a` is a tensor created in webppl and `b` is a tensor created in JavaScript, then operations like `T.sub(a,b)` return NaN.

**Comment by null-a** [comment]
The issue here was that if you `require('adnn/tensor')` from JS, then tensors created in JS have a different constructor instance to those created a webppl. This breaks `instanceof Tensor` checks in adnn. I think one hacky work-around is to rely on the fact that webppl happens to add `ad.tensor` as a global.

**Comment by null-a** [comment]
There's no obvious outstanding action here, so I'm closing the issue. The suggested workaround is still the best way I know of to deal with the original problem.
