### ISSUE TITLE
Compute guide distributions lazily / on-demand?

### ISSUE THREAD

**Issue by dritchie** [probmods/webppl#652]
Currently, guide distributions are always computed, even if the program is running under a coroutine that does not use guides. When the guide construction is compute-intensive (e.g. involves big neural nets), this seems wasteful.

It might be better to encapsulate the guide in a thunk which is only evaluated when the guide is actually needed.

**Comment by ngoodman** [comment]
this also comes up for dream / sleepey training. we need to forward sample the part of the program inside mapData without guides. we could run the guide anyway, but the inputs to data-dependent guides will be undefined.

**Comment by null-a** [comment]
I like this idea.

Not only because it helps avoid wasted computation, but it's a way of introducing at least *some* separation between the guide and target programs.

Another way we might take advantage of this, is by only allowing `param` to be called from within (the dynamic extent of) one of these guide thunks. This would make the fact that it's the *guide* that should be parameterized *much* clearer.

(Of course, we have our `modelParam` trick as an escape hatch, so we can still indirectly parameterize the target if we wish. I imagine we may also need an additional helper or two to extract bits of optimized guides for use as normal functions.)

This needs thinking through properly of course, but my first impression is that it's worth exploring.

**Comment by null-a** [comment]
I've started work on this [here](https://github.com/null-a/webppl/tree/guide-thunks).

**Comment by null-a** [comment]
In trying out #715, I realized that some guide computations can't easily be placed within the current guide thunks. In particular, when the guide is recurrent, we usually want to perform some guide computation *after* `sample` has returned, and this isn't easily accommodated.

```js
// dev
var val = sample(dist(), {
  guide: guideDist(computeParams(...))
});
globalStore.ctx = update(globalStore.ctx, val);

// guide-thunks
var val = sample(dist(), {guide() {
  return guideDist(computeParams(...));
}});
// still executed by all inference algos:
globalStore.ctx = update(globalStore.ctx, val);
```

(You could think about waiting until the next guide thunk before doing the update, but I expect that would get messy quickly.)

The obvious extension to the current approach would be to allow guide thunks to be run at any point in the program, not only at random choices.

```js
var val = sample(dist(), {guide() {
  return guideDist(computeParams(...));
}});
guide(function() {
  globalStore.ctx = update(globalStore.ctx, val);
});
```

Looking at this, one interesting question that comes to mind is whether `guide` would return the value of the thunk when it's evaluated. If it doesn't, the only way to thread the context through the model is via the global store, which forces a very clear separation between the guide and the target.

(I'm not advocating this approach, I think it still needs more thought, but I figured it was worth writing down.)

**Comment by null-a** [comment]
Re-opening for discussion of previous comment.

**Comment by dritchie** [comment]
I like the approach of having `guide` run anywhere, and I have no objection to `guide` returning the value of the thunk. This would permit the most design flexibility on the part of the user, anyway. Are there any reasons why we'd want to forbid this?

**Comment by null-a** [comment]
Here's what I see as the main problem with the *use* of return values from the proposed `guide` method:

Since the guide is run conditionally (depending on which inference strategy is used) the return value from `guide` will either be the result of running the guide or `undefined`, say. In general, programs will need to be written to handle both cases if they are to work across multiple algorithms without error. Fail to do this correctly, and you're now set up for problems should you choose to switch algorithms in the future.

> This would permit the most design flexibility on the part of the user, anyway. Are there any reasons why we'd want to forbid this?

Even if we don't return a value from `guide`, I don't think we are preventing any particular model/guide structure from been used, so I think it might be better to think of this in terms of which things we make easy and which things we make difficult.

By not returning a value from the `guide`, I think we'd be encouraging users to write their program in such a way that the model can be run successfully without the guide. This seems useful to me.

Of course, there are other options too. For example we could return a value from `guide`, but warn against its use in the documentation. (Though this is less appealing to me at the moment.)

I guess one way to move forward with this would be to start by not returning a value from `guide` to see how it works in practice. If we later decide we need the return value, adding it is likely to be a non-breaking change.

**Comment by null-a** [comment]
Related to the previous comment: When you start using the global store, it becomes possible to unwittingly break the independence assumption used by `mapData`? So it might be a concern if the presence of the proposed `guide` method had the effect of encouraging the use of the store as a means of threading the guide state through the program. In practice though, I think the store will usually be used for this anyway (since our only other alternative right now it to thread the state through the program as an extra argument) so this is probably not a concern.
