### ISSUE TITLE
Parameter-server interface for params

### ISSUE THREAD

**Issue by ngoodman** [probmods/webppl#660]
After thinking about a extensions of the system to allow asynchronous distributed parallelism, at least for VI, I'm leaning toward refactoring the params to live in a global store (rather than passing local params objects, which I've previously championed).

By doing this and making a suitable API for the params store (something along the lines of `getParam(name)`, `setParam(name, value)`, `incrParam(name, delta)`), we could back the params by local memory, shared memory, or a network based protocol. This would allow pretty easy implementation of parallel workers....

**Comment by stuhlmueller** [comment]
Here's one way to go about this:

1. Adapt the [adnn optimization methods](https://github.com/dritchie/adnn/blob/master/opt/methods.js) so that we can get back raw deltas.

2. Implement a parameter store (initially in-memory) that supports the following functions:
   
    - `getParams(id) -> params`
    - `setParams(id, params) -> void`
    - `incParams(id, deltas) -> void`

    Here, `id` is the name for a set of parameters. `params` has the same format as in the current implementation, with a name for each parameter. The parameter set ID is used to support storing multiple sets of parameters for the same program (e.g. for different runs), and to allow multiple programs to use the same simple parameter names (like `mu`). This matters most for a network-based parameter store that is used by multiple programs. By default, it could be set to a unique ID that is generated when webppl is started (so there's no re-use across runs), but alternatively we could support setting it using a command line parameter (like the random seed). If we have a runner that starts multiple parallel webppl processes, it could set this ID such that it is the same for each process.

3. At the beginning of each `Optimize` iteration, call `getParams` to retrieve the current params from the store. This replaces the current functionality for passing in `params` via `options`.

4. When an `Optimize` iteration ends:

    1. If parameters were empty at the beginning of the iteration, call `setParams` with the newly initialized parameters.

    2. Call `incParams` using the deltas from the optimizer. 

The current functionality for returning new parameters from `Optimize` goes away; instead the parameters can be retrieved using `getCurrentParams()`, which calls `getParams` with the ID for the active program execution.

Instead of having `incParams` return nothing, we could also have it return the store's current parameter set and thus merge steps 3 and 4.2 on every iteration except for the first. 

This differs from Noah's suggestion in that it only allows all parameters for a program to be set in batch. I'm not sure if this is better or worse. I mainly explored it because it seems like such a small divergence from our current implementation, but some form of batching is desirable for network-based storage anyway. Are there significant advantages to having the API be per-parameter?

**Comment by null-a** [comment]
> Are there significant advantages to having the API be per-parameter?

Is the following a case where we need the per-parameter methods, or something similar:

If we encounter a never-before-seen parameter in the middle of optimization, then we'll want to `incParams` for the parameters we have seen before, but we'll need to do something like `setParam` for the new parameter?

**Comment by stuhlmueller** [comment]
Good point - this is an issue that needs to be addressed!

One option would be to allow `setParams` to set a subset of all parameters, and to do what you suggest at the end of an optimization step for all new parameters. This doesn't seem ideal though—what if another thread has encountered (and set) this parameter in the meantime? In this case, we'd prefer to only apply a delta.

So, another option would be to always have `incParams` also take the current parameters (pre-update) as an argument; i.e. `incParams(id, params, deltas)`. The store would then initialize any params it hasn't seen before using the given values, but otherwise ignore `params` and only use the deltas.

**Comment by null-a** [comment]
I believe #708 closes this.
