### ISSUE TITLE
Refactor and document how to include webppl boxes and scripts in web pages

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#70]

**Comment by null-a** [comment]
There's possibility this feature could be extracted as a package/module. (#123)

**Comment by longouyang** [comment]
I've been working on refactoring the webppl boxes code in a package: [webppl-editor](http://github.com/probmods/webppl-editor)

The existing results rendering code is not very responsive because there's never time to render to the DOM. So even if the call to build graphs / print statements is made at the beginning of the webppl code, it doesn't show up for the user until after webppl execution.

So I decided to place model execution in a Web Worker (as well as write code editors as React components). This appears to work well and feels more responsive than the existing editor. Can you guys play around with [this demo](http://web.stanford.edu/~louyang/wp-editor/index.html), peruse the code, and offer feedback?

A list of changes:

- Because webppl happens on a different thread, you can now click run on multiple code boxes (it's currently all queued through a single worker though)
- For graphics, I switched from highcharts to vega (to be consistent with Erin's webppl-viz package, which Noah would like to integrate)
- You can now right click rendered graphics and download them to disk.

Todos:

[ ] Switch to the browser.js versions of webppl run and compile methods (so that packages included in webppl get bundled)
[ ] Get code folding working
[ ] Get bracket matching working
[ ] Get vanilla JS execution working
[ ] Translate the dippl Draw functions so that the computer vision examples work with the new editor setup (this might be hard?)
[ ] More robust stringifying, error catching (so that, e.g., just typing `flip` and clicking run returns something like `Function flip() { ... }` rather than `DataCloneError`
[ ] Write a `density()` visualizer?
[ ] Implement an inference progress interface? This would further improve the user friendliness of the editor.
[ ] At some point I had dynamic stuff working through vega (e.g., showing an exact count when you hover over a histogram bar) but then it mysteriously stopped; try to get this working again
[ ] Write the literate code editor? (i.e., the widget that lives at webppl.org) Though maybe this could just be bespoke code for webppl.org

**Comment by stuhlmueller** [comment]
I like the web workers idea and resulting responsiveness!

I'd try to get rid of the jQuery dependence. React works best if the DOM state is a pure function of the state of the React components, but this is no longer true if you manipulate it using jQuery. This can easily lead to difficult-to-debug bugs down the road, and I'm not convinced it's necessary here. For example, the `run` button should just be its own component, with updates happening as a consequence of its `props` changing.

**Comment by longouyang** [comment]
I've managed to reduce, but not eliminate, dependency on jQuery.

I'm uncertain about the best way to Reactify [this vega call](https://github.com/probmods/webppl-editor/blob/3abe22b49e8647a4804124685363c220f43dfd15/src/index.js#L165).. thoughts?

**Comment by null-a** [comment]
I like it, feels very nice to use!

> Implement an inference progress interface?

**Comment by null-a** [comment]
> Implement an inference progress interface?

This sounds like it's related to the callbacks/hooks idea. I've added a comment to #197 describing a possible direction that might go. Does that sound like something you could make use of here?

**Comment by longouyang** [comment]
> This sounds like it's related to the callbacks/hooks idea. I've added a comment to #197 describing a possible direction that might go. Does that sound like something you could make use of here?

Possibly, though I think the fit with the current editor architecture could be improved.

The current editor is composed of:

- A main thread (editor.js) which manages code boxes with CodeMirror and React.
- A worker thread with two pieces: some lightweight management stuff (worker.js) and webppl (webppl.js is imported into the worker using the somewhat weird `importScripts` function)

The main thread can only coarsely direct the worker -- it can only tell it to run a model.
The worker reports back by sending messages (lightweight representations of e.g., text, charts, errors) that the main thread renders with React.

We might implement inference progress bars by explicitly passing in hooks in our webppl model:

```js
Enumerate(
  model,
  500,
  {init: function() { progressBar("started enum") } ,
   iteration: function(trace) { globalStore.iter = globalStore.iter + 1; progressBar(globalStore.iter) },
   finish: function() { progressBar("finished enum" })
```

Where `progressBar` is a function in worker.js that talks to the main editor thread. But:

- This doesn't actually work. As proposed, inference hooks are supposed to be js, not webppl.
- It'd be nice if we got progress bars for free, rather than having to declare hooks in our inference code.

I think the current editor would play better with a system where inference methods simply trigger global events and there are some default event listeners that make progress bars when a browser is around. Of course, the editor architecture isn't set in stone either, so we might also modify the editor to fit hooks rather than the other way around.

**Comment by longouyang** [comment]
On further thought, the fit might be better than I thought. We could provide wrapper versions of inference methods in worker.js that specify the hooks.

**Comment by null-a** [comment]
I was imagining that at worse we'd have something like:

````js
MCMC(model, { samples: 100, callback: editor.progressBar() })
````

And if the callback interface was shared by all inference routines we could perhaps improve this by making it possible to register global callbacks. I've not thought about this much, but perhaps we could do this outside of the language like so:

````js
webppl.callbacks.push(editor.progressBar)
````

This is perhaps not all that different from your global events idea. I guess I need to think about whether the events based approach would work for the other use cases people might have for callbacks. (Since I doubt we need both callbacks and events.)

Are you imagining having progress indicators per-code box, or a global one for the currently executing webppl program?

**Comment by longouyang** [comment]
> Are you imagining having progress indicators per-code box, or a global one for the currently executing webppl program?

Separate indicators per code box. Right now, though, because all execution is queued through a single web worker, the two options are essentially the same. Additionally, if we move to multiple workers, each one hosts its own copy of webppl, so it looks like "a global one for the currently executing webppl program" always entails "progress indicators per code box".

I think only-local hooks could work for now, and we can try out global hooks if there's need.

**Comment by longouyang** [comment]
Unfortunately, it looks like using Web Workers for the editor revamp won't work.

I've discussed with Andreas and I think we agree that it takes too much work to integrate DOM libraries. Workers don't have a DOM, so you have to move any such computations to the main thread and manage communication between worker and main thread using `postMessage`. Also, in some informal testing with the dippl computer vision examples, this architecture is noticeably slower than the old approach.

We should move back to a single thread, although we can keep the responsiveness that Web Workers provide by using a browser-only trampoline that pauses every n milliseconds to allow DOM updates to happen. See PR #289

I've done a couple measurements and the new pausy trampoline doesn't seem introduce substantial overhead.

I measured total computation time for a very simple model:
```
util.seedRNG('a')
repeat(5e4, flip)
```

Time spent in:
- Old trampoline: M = 1357 ms, SD = 18 (N = 5)
- Pausy trampoline: M = 1340 ms, SD = 54 (N = 5)

I also measured a much realer example, the final dippl computer vision example..

Timings:
- Old trampoline: M = 3865 ms, SD = 204 (N = 6)
- Pausy trampoline: M = 3846 ms, SD = 154 (N = 6)

**Comment by longouyang** [comment]
Just writing an update so that we have a decent paper trail.

The editor that assumes a pausy trampoline has proven to be viable (e.g., adapting the dippl Draw functions was very easy under this setup), so we'll go with that.

There's still some under-the-hood refactoring to do (React, CSS) but webppl-editor is now usable.

Should we close this issue?

**Comment by hawkrobe** [comment]
Should there be some mention of the editor package (and how to use it) in the webppl docs? I see the usage documentation in the webppl-editor package README, but there's nothing in the webppl docs that would tell you webppl-editor exists, right?

**Comment by longouyang** [comment]
Ah -- good call. I'll add that to my todo list.

**Comment by longouyang** [comment]
PR created in #359
