### ISSUE TITLE
Change how optMethod is passed to Optimize (re: interleaving different estimators)

### ISSUE THREAD

**Issue by dritchie** [probmods/webppl#702]
There are situations where it would be useful to stop and restart `Optimize`, potentially with different estimators (e.g. repeatedly alternating between Dream sampling and Dream learning, possibly with some ELBO steps thrown in as well). The current interface to `Optimize` allows this, with one hiccup: any state being tracked by the optimization method (e.g. step sizes, momenta) is lost.

I think the simplest way to overcome this issue is to change the way optMethod is passed to `Optimize`. If we switch from the current style to just literally passing in the thunk returned from e.g. `opt.adam`, then things should work out: these thunks close over their state, so if we pass the same thunk to multiple subsequent `Optimize` calls, the same state will be used (and updated each time).

Any objections? I realize that this technically exposes a regular JS thunk to webppl code, but from the user's perspective, it's just an opaque "optimization method" object.

(@dorarad: this idea just occurred to me, and I think it's even simpler than the one we had talked about before).

**Comment by dorarad** [comment]
Are there other cases currently in which a JS thunk is exposed to webppl code so far? I wonder if doing so resonate with the current high-level purely-functional style of webppl.

**Comment by dritchie** [comment]
Just to clarify: what I meant was that user code would have a reference to backend JS function, but the user would never be expected to call it, or even know that it's a function. From the user's perspective, it's just an opaque object.

**Comment by dorarad** [comment]
Yea I understood, and I personally like the idea. Still, I wonder if there are previous cases of exposure of a js thunk back to the user, regardless of what we expect his perspective to be, and whether its compatible with current interface and style of webppl.
On the other hand, we may not have other good alternatives so maybe it is the best way to go about it.

Would also be happy to hear @null-a's and @stuhlmueller's thoughts!

**Comment by stuhlmueller** [comment]
The main drawback I see for this approach is that we don't have explicit access to the state, so we can't serialize it and resume computation from where we left off if we stop and restart webppl, or if we want to copy the optimization state over to another process.

A potentially relevant consideration is that, once we merge the `param-store` branch, `Optimize` will no longer return anything, since there is a single global parameter store (see #660). Paul and I discussed the possibility of having `Optimize` return its state (step sizes, momenta, etc.) in serializable form and add an option to `Optimize` that takes such state as input.

**Comment by dritchie** [comment]
Ah, yeah, I figured this would interact with `param-store`--probably best to wait until that's done.
