### ISSUE TITLE
Investigate overhead in forward-sampling from guided models

### ISSUE THREAD

**Issue by hawkrobe** [probmods/webppl#795]
I'm working with a model that is taking a prohibitively long time to run (where I have to run inference many times for different data), and Noah suggested I look into how much computation time was being spent optimizing vs. forward sampling from the model, respectively. I constructed a simpler model and did a few tests:

```
var softplus = function(x) {
    return Math.log(Math.exp(x) + 1);
};

// takes a sample from a dirichlet distribution for each word,
// representing the extent to which that word describes each object
var stringProbPrior = function(){
  var meanings = map(function(utt) {
    return sample(Beta({a: 1, b: 1}), {
      guide() {
        return Beta({a: softplus(param({name: 'beta_a_' + utt})),
                     b: softplus(param({name: 'beta_b_' + utt}))});
      }
    });
  }, ['w1', 'w2']);
  return _.zipObject(['w1', 'w2'], meanings);
};

var model = function() {
  var lexicon = stringProbPrior();
  mapData({data: globalStore.data}, function(datum){
    observe(Categorical({vs: _.keys(lexicon), ps: _.values(lexicon)}), datum);
  });
  return lexicon;
};

globalStore.data = ['w1', 'w1', 'w1', 'w1', 'w1'];

var opt = timeit(function() {
  Optimize({model: model,
            method: 'optimize', steps: 10000, verbose: false,
            optMethod: {adam: {stepSize: .1}}});
});
console.log("optimizing params: " + opt.runtimeInMilliseconds);

var res1 = timeit(function() {
  Infer({method: 'forward', samples: 10000, guide: true, model: model});
});

console.log("forward sample from model w/ guide: " + res1.runtimeInMilliseconds);

var res2 = timeit(function() {
  Infer({method: 'forward', samples: 10000, guide: true, model: function() {return stringProbPrior();}});
});

console.log("forward sample directly from posterior w/ guide: " + res2.runtimeInMilliseconds);

var baseline = timeit(function() {
  Infer({method: 'forward', samples: 10000, model: function() {
    var meanings = map(function(utt) {return beta(1,1);}, ['w1', 'w2']);
    return _.zipObject(['w1', 'w2'], meanings);
  }});
});

console.log("forward sample from prior (baseline): " + baseline.runtimeInMilliseconds);
```

The results are:

```
optimizing params: 2598                              
forward sample from model w/ guide: 1169             
forward sample directly from posterior w/ guide: 629 
forward sample prior: 257                            
```

There are a couple interesting things here: 

1. It takes ~2x longer to sample from the guided model than directly sampling from the posterior (the only difference is the `mapData` with `observe` statements that should be ignored). 
2. It takes ~2x longer to sample directly from the posterior (using the learned params) than to sample from the prior (not using any learned params).

Do we know what could be causing this overhead? These ratios seem invariant with the number of samples (so it's not a fixed up-front cost), and it definitely adds up when you have to optimize & forward sample many times for different datasets.

**Comment by null-a** [comment]
At first glance, these results don't seem too surprising to me. Starting from "forward sample prior" and working up your list, each change made to the program incurs extra work on the back end.

> It takes ~2x longer to sample from the guided model than directly sampling from the posterior (the only difference is the mapData with observe statements that should be ignored).

These `observe`s *are* ignored, but they aren't optimized away, sadly. I expect the increase in run time comes from evaluating the `mapData`.

> It takes ~2x longer to sample directly from the posterior (using the learned params) than to sample from the prior (not using any learned params).

There's more work to do in the version that samples from the guide. In particular, I expect that the calls to `param` account for most of the increase in run time.

So, I think I understand where you're coming from. It probably is the case that in principle these 2x increases in run time could be made to go away with enough optimization work, but we haven't done much of that thus far. (Does this sound about right, or am I missing something?)

None of this helps fix your original problem of course! I imagine you can structure your code so that you don't run `mapData` unnecessarily if that's causing you problems. As for `param`, how confident are you that the factor of two highlighted here is the bottleneck in your full program? If you share the code, I'd be happy to take a look.

Aside: You might consider using a [`LogitNormal`](http://docs.webppl.org/en/master/distributions.html#LogitNormal) distribution to guide the `Beta`, if you've not already done so. The `Beta` distribution doesn't support reparameterization, but the `LogitNormal` does, so optimizing the ELBO is likely to work better with the latter.

**Comment by hawkrobe** [comment]
@null-a Thanks for the breakdown of where the extra work is coming from -- I don't think you're missing anything. It might be fair, then, to change the title of this issue to something like "optimize back-end for guided forward-sampling" if you expect that optimization work would be useful to do at some point?

The tips on workarounds are also very helpful (especially about reparameterization and the LogitNormal, which I didn't know about!) I'm not sure this is *the* bottleneck, but because every sample I get from my larger cognitive model has to run variational and forward-sample from the resulting guide K times (to update agent beliefs after each time step), it does add up to a pretty substantial time cost. [Here's](https://github.com/hawkrobe/reference_games/blob/master/models/tangrams/arbitrariness.wppl) the model if you can spot other bigger bottlenecks?

**Comment by null-a** [comment]
Ahead of time, I'd be surprised if there was anything significant to be gained (on your model) from optimizing the forward sampling coroutine *itself*. Of course, *it is* possible that your program is spending a lot of time forward sampling from some model or other. But if this is the case, my guess would be that most of that time was spent in the model itself, rather than in the coroutine[1]. To make it faster, I'd expect to have to make the model more efficient.

Thanks for sharing your code. Running it as is, here's where time is spent:

```
Optimize                   | 18.5s
Infer({method: 'forward'}) | 1.6s
Other                      | 0s
Run time                   | 20.1s
```
(Measured by adding `console.time`/`console.timeEnd` calls.)

This is confusing to me. As written, the majority of the time is spent in `Optimize`, so how did forward sampling become the focus of attention? (Perhaps because in practice the ratio of optimization steps vs. forward samples is different?)

[1] Although there is at least one way to spend a lot of time in the coroutine -- have the return values of the program be big JS objects, as these are slow to serialize. That doesn't seem to be something we need to worry about here though.

**Comment by hawkrobe** [comment]
> As written, the majority of the time is spent in Optimize, so how did forward sampling become the focus of attention? (Perhaps because in practice the ratio of optimization steps vs. forward samples is different?)

Right, I cranked down the number of forward samples in each inference quite a bit (from 1500 to 250) to save time while iterating on the model, since I'm more comfortable interpreting the impact of skimping on forward samples than skimping on optimization steps. I've also found several other ways of optimizing the model itself since creating this issue, so if you don't think there are any savings to be found forward-sampling from guides, feel free to close this!

>Ahead of time, I'd be surprised if there was anything significant to be gained (on your model) from optimizing the forward sampling coroutine itself.

I was just thinking it might be nice to keep an issue open for the more basic, obvious optimizations you mentioned above (e.g. ignoring `observe` statements when sampling from the guide, or somehow making calls to `param` take less time).
