### ISSUE TITLE
Make webppl kernel for ipython notebook

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#84]
Adapt Javascript kernel: https://www.npmjs.com/package/ijavascript

**Comment by ngoodman** [comment]
There is also some demand for R integration. R seems to play reasonably nice with javscript, so it should be possible to expose a webppl function that just calls out to the webppl runtime. To make this nicest we'd want to be able to pass in R variable values (e.g. as json objects) and get out some reasonably idiomatic R structure (ERP as a model?). I'm not sure how much work this would actually be...

@mcfrank suggested this and suggested that it would enable interactive use with [shiny](http://shiny.rstudio.com/).

Also see what the Stan project does in terms of interfacing with R.

**Comment by stuhlmueller** [comment]
It's natural to interact with R from ipython notebooks ([example](http://nbviewer.ipython.org/github/ipython-books/cookbook-code/blob/master/notebooks/chapter07_stats/08_r.ipynb)), so maybe we can copy that strategy.

**Comment by pedir** [comment]
There's Beaker (http://beakernotebook.com) which seems to be exactly offering lab notebook style code execution with multiple language interface. I don't have much experience with it, but I think they expose some global beaker object, which can be accessed with different languages like R, Python, JS out of the box.

They have support for JS, so it shouldn't be hard to modify that so that it works with webppl.
