### ISSUE TITLE
Sample from a Dirichlet with random K?

### ISSUE THREAD

**Issue by insperatum** [probmods/webppl#853]
Is this possible?

My code:
```javascript
var f = function() {
  var K = sample(RandomInteger({n:8})) + 2
  print("sampled K=" + K)
  var ones = map(function() {return 1}, _.range(K))
  var dir = sample(Dirichlet({alpha:Vector(ones)}))
  print("returning K=" + K)
  return K
}

print(Infer({method:"MCMC", samples:10}, f))
```

Returns:
```
sampled K=8
returning K=8
sampled K=2
sampled K=2
sampled K=7
sampled K=6
returning K=8
sampled K=3
returning K=8
sampled K=5
sampled K=6
{"probs":[1],"support":[8]}
```

**Comment by null-a** [comment]
The problem here is that MCMC (single site MH) can't explore the whole space, since any proposal to change K is always rejected. This is because when K changes, the dimension of the Dirichlet changes, so the probability of the previous value of `dir` is always zero. (I'm happy to expand on this if that doesn't make any sense.)

I can think of a couple of things to try. (And there are likely more things I'm not aware of.) One is to switch to a different inference algorithm, such as SMC. Another is to build the Dirichlet sample from a bunch of gamma samples, which would side step the problem with single site MH. More specifically, I'm imagining using something like this instead of `sample(Dirichlet())` for example:

```js
var myDirichlet = function(a,k) {
  var x = repeat(k, function() {
    gamma(a,1)
  })
  var s = sum(x)
  return map(function(xi) { return xi / s; }, x)
}
```

**Comment by insperatum** [comment]
Okay great thanks! Using a bunch of gamma samples sounds like a good way to go.

Just to fill out my comprehension of what's going on - could you help me understand the circumstances under which MH is actually 'single site', and the times when it also resamples dependent variables. Or rather, what are the circumstances under which webppl considers variables to be the same ones as in the previous step.

For example, when is it that a `map` decides it's time to resample elements? Is it whenever the domain changes? Whenever the length of the domain changes?

Thanks for your help :)

**Comment by null-a** [comment]
It's always single site, in the sense that each proposal picks a single `sample` statement encountered in the previous execution, and resamples its value. The program is then re-run from the chosen `sample` statement, reusing the values from the previous execution for the remaining `sample` statements where possible. The [dippl mcmc chapter](http://dippl.org/chapters/06-mcmc.html) has more on this. Hope that helps.
