### ISSUE TITLE
Fix typo in gradient.js require

### ISSUE THREAD

**Issue by superlaza** [probmods/webppl#874]
On L2:C21 of `src/inference/dream/gradient.js`

`var ad = require('..../ad');`

is missing a forward slash.

**Comment by superlaza** [comment]
Fix on dev branch, broken on npm release

**Comment by null-a** [comment]
Hi, thanks for mentioning this.

`gradient.js` is automatically generated from `gradient.ad.js` when the package is installed, and it's possible the `ad` import is getting messed up as part of that.

I've just installed the latest npm release locally, after which `gradient.js` was correct for me. Would you be able to uninstall/reinstall the webppl package and check whether the require in `gradient.js` is still wrong? If so, perhaps this is a problem specific to a particular node version or OS etc.

Thanks!

**Comment by spw1016** [comment]
I just installed webppl through npm and it threw an error because of the var ad definition on line 2 in gradients.js. The ad variable was defined twice, though, so I just commented out the first one and it now works. 
`'use strict';
//var ad = require('..../ad');
var assert = require('assert');
var _ = require('lodash');
var guide = require('../../guide');
var ad = require('../../ad');
module.exports = function (env) {`

**Comment by null-a** [comment]
@spw1016 Thanks for reporting this! Looks like there might be a problem in Windows, I'll look into it.
