### ISSUE TITLE
Add .toString() to erps

### ISSUE THREAD

**Issue by stuhlmueller** [probmods/webppl#89]
Pretty-print distributions

**Comment by stuhlmueller** [comment]
(Or add some other way to print out erps on the command line in a readable form.)

**Comment by iffsid** [comment]
One thing to consider while doing this is to check the support type of the erp.
If the support type is real-valued, it's perhaps better to draw a scatter plot (in the browser), or display summary statistics (in either) rather than unconditionally display the erp (with a bar chart, or (support, prob) pairs).
(This could even be extended to non-real-valued supports, when the distribution simply has too many support elements for a bar chart to be sufficiently interpretable)

**Comment by null-a** [comment]
@iffsid added `ERP.prototype.print` in #162. Does that address this, or did you have something else in mind?

**Comment by stuhlmueller** [comment]
Yes, that resolves it.
