### ISSUE TITLE
Add toArray method to distributions

### ISSUE THREAD

**Issue by smihael** [probmods/webppl#900]
Calling Infer by default prints marginalized probabilities.
` Infer ( function () { return flip (0.9) ? "a" : "b" })`
would print: 

```
Marginal:
    "a" : 0.9
    "b" : 0.1
```

I investigated source code and found out that under to hood .print() is called in [src/dists/marginal.ad.js](https://github.com/probmods/webppl/blob/dev/src/dists/marginal.ad.js)

It would be very practical to have something like .toArray() as well in all dist objects, so that users can easily  programmatically determine argMax etc.

Something like:
```
function toArray(dict) {
    map(
       function(key){ return {state: key, score: dist.score(key)} },
       dist.support()
    )
}
```
would perfectly  suffice.

**Comment by null-a** [comment]
I'm not sure whether you realise this, but it's already possible to write things like `toArray` or `argMax` (for distributions with finite support) from within WebPPL. For example:

```js
var distToArray = function(dist) {
  return map(function(x) {
    return {value: x, score: dist.score(x)}
  }, dist.support());
}
distToArray(Bernoulli({p: 0.4}))
// => [{"value":true,"score":-0.916290731874155},
//     {"value":false,"score":-0.5108256237659907}]
```

So I'm not sure that adding `toArray` would buy us much?

**Comment by null-a** [comment]
I think it would be fine to add `toArray()` if it's useful, but at the moment I'm not sure that it is. I think `argMax` is probably better implemented directly in terms of `dist.support()` and `dist.score()` (since doing so avoids the intermediate array generated by `toArray()`), and I'm not aware of any other use cases. I'll close this issue for now, but don't hesitate to re-open it if you have additional use cases that make this worth while.

(Aside: I think the undocumented `dist.MAP()` may be your `argMax`, and probably ought to be renamed accordingly and documented. See #140.)
