### ISSUE TITLE
HMC samples out of support

### ISSUE THREAD

**Issue by hawkrobe** [probmods/webppl#912]
This may be a case of #343? Here's a simple program that (often but not always) errors with `Parameter "p" should be of type "real [0, 1]"` and if you print out the offending variable, it's often slipping above 1. 

```
var inferOpts = {method: 'MCMC', kernel: {HMC: {steps: 50, stepSize: .01}},
                 samples: 5000}
var results = Infer(inferOpts, function() {
  var p1 = uniform(0.5, 1)
  var p2 = uniform(0, p1)
  if(p2 > 1) {
    print(p1)
    print(p2)
  }
  observe(Bernoulli({p: p2}), false)
  return p1
})
```
This runs ok with the MH kernel.

**Comment by null-a** [comment]
This looks like a new (i.e. previously unnoticed) bug that occurs when the constraints on a distribution's support depend on a sampled value. The problem is that after taking a step, we check whether the value has remained within its distribution's support, but when we do so we fail to account for the fact that the bounds on the support may be ad-ified values (as they are here) rather than plain numbers. If this diagnosis is correct, I think the fix would be to make [this change](https://github.com/null-a/webppl/commit/7b51a9193b59826e086079a452c1eda4d515c9cd). I'll open a pull request to address this in a day or two.
