### ISSUE TITLE
Creating a new distribution ? Combinatorics ?

### ISSUE THREAD

**Issue by vsraptor** [probmods/webppl#942]
How do you create a new distribution ?
I'm wondering if I have probability like : 

    P(x) = 1 / (N choose M)

As I understand u somehow have to implement .score() and .sample() ?

Also will sampling/marginalization works for larger M and N ?

**Comment by null-a** [comment]
Yes, you need to make a new distribution object, and a minimal implementation is mostly just implementing see `score` and `sample`. The main thing I wanted to say is that there are some vague pointers about all this [here](https://github.com/probmods/webppl/issues/910#issuecomment-426926853).

> Also will sampling/marginalization works for larger M and N ?

I'm don't know what distribution you have in mind, possibly because non of this stuff is fresh in my mind, so I don't know what `sample` looks like. Marginalization is implemented by the inference algorithms.
