### ISSUE TITLE
.some() method behaves unexpectedly 

### ISSUE THREAD

**Issue by bwaldon** [probmods/webppl#945]
The following code returns `true` in the online WebPPL interpreter, but should return `false`: 
```
var array = [{x:"x1", y:"y1"}, {x:"x1", y:"y2"}]

console.log(array.some(function(item){
  return(item.x === "x1" && item.y === "y3")
  }))
```

**Comment by null-a** [comment]
The problem here is that (a) `array.some` is calling out to a JS function and (b) the JS function is passed a webppl function as an argument, which isn't supported -- see point 2 [here](https://webppl.readthedocs.io/en/master/language.html#calling-javascript-functions). (Of course, it would be nice if this was an error of some kind.) Instead, you can use the webppl function `any`. (Docs [here](https://webppl.readthedocs.io/en/master/functions/arrays.html#any).)

**Comment by bwaldon** [comment]
Missed this in the documentation — thanks!
